alias: Dehumidifier Night Run Cold Weather
triggers:
  - trigger: time
    at: "04:00:00"
conditions:
  - condition: template
    value_template: "{{ state_attr('weather.forecast_home', 'temperature') | float <= 5 }}"
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.dehumidifier_em_switch_power
            below: 10
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index <= 3 }}"
                - condition: numeric_state
                  entity_id: sensor.dehumidifier_em_switch_power
                  below: 10
              sequence:
                - action: switch.turn_on
                  target:
                    entity_id: switch.dehumidifier_finger_bot
                - delay:
                    seconds: 15
                - choose:
                    - conditions:
                        - condition: numeric_state
                          entity_id: sensor.dehumidifier_em_switch_power
                          below: 10
                      sequence:
                        - delay:
                            seconds: 45
  - delay:
      minutes: 60
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.dehumidifier_em_switch_power
            above: 10
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.dehumidifier_finger_bot
mode: single
